dist: trusty
sudo: required

language: python

python:
  - "2.7"

addons:
  postgresql: "9.4"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/caffe

  before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install -r requirements/dev.txt
  - . $HOME/.nvm/nvm.sh
  - sh requirements/caffe_tensorflow_keras_install.sh
  - nvm install stable
  - nvm use stable
  - npm install

before_script:
  - export PYTHONPATH=$PYTHONPATH:$HOME/caffe/caffe/python
  - export LD_PRELOAD="/usr/lib/libtcmalloc.so.4"
  - psql -c "CREATE DATABASE fabrik" -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD 'fabrik'" -U postgres
  - psql -c "ALTER ROLE admin SET client_encoding TO 'utf8'" -U postgres
  - psql -c "ALTER ROLE admin SET default_transaction_isolation TO 'read committed'" -U postgres
  - psql -c "ALTER ROLE admin SET timezone TO 'UTC'" -U postgres
  - psql -c "ALTER USER admin CREATEDB" -U postgres

script:
  - flake8 ./
  - npm run ci
  - coverage run --source=caffe_app,keras_app,ide/utils manage.py test

after_success:
  - coveralls
